// Code generated by oxygen. DO NOT EDIT.

package test

import "reflect"

// Marshaller is the interface implemented by types that can marshal themselves into valid TEST.
type Marshaller interface {
	MarshalTEST() ([]byte, error)
}

// IsMarshaller attempts to cast the value to TEST Marshaller interface,
// if so, returns a marshal function.
func (e *engine) IsMarshaller(rv reflect.Value) (func() ([]byte, error), bool) {
	if i, ok := rv.Interface().(Marshaller); ok {
		return i.MarshalTEST, ok
	}

	return nil, false
}

// Unmarshaler is the interface implemented by types that can unmarshal TEST description of themselves.
type Unmarshaler interface {
	UnmarshalTEST([]byte) error
}

// IsUnmarshaler attempts to cast the value to TEST Unmarshaler interface,
// if so, returns an unmarshal function.
func (e *engine) IsUnmarshaler(rv reflect.Value) (func([]byte) error, bool) {
	if i, ok := rv.Interface().(Unmarshaler); ok {
		return i.UnmarshalTEST, ok
	}

	return nil, false
}
